name: Sweepstakes
on:
  pull_request:
    branches:
      - main
    paths:
      - exec.txt

jobs:
  sweepstakes:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "15.10.0"

      - name: Install Dependencies
        run: yarn install --foce --frozen-lockfile

      - name: Build Project
        run: yarn run build

      - name: Run
        run: node ./dist/index.js
